### ISSUE TITLE
First pixels at lower temperature in some readings

### ISSUE THREAD

**Issue by danilotomaccio** [m5stack/M5StickC-Plus-TLite-FW#3]
### Describe the bug

Approximately one reading yes and one no, the first two pixels of the first line and the first of the second are at minimum temperature. In readings where it does not happen, the reading is correct.
The result is that when the pointer is set to the minimum temperature it moves continuously from the upper left side to the point of actual lower temperature.
I haven't been able to find much information about the T-Lite online and especially on the community so I haven't been able to understand if this is a problem that only occurs on my device or if it is actually a bug (but it could be a software bug since the defect occurs intermittently and when it is not present the readings are correct)

### To reproduce

Just turn on the device with this firmware (both on version 0.0.5 and 0.0.7)

### Expected behavior

Correct readings at each reading

### Screenshots

![Tlite4](https://user-images.githubusercontent.com/21012635/228972480-90671e38-974f-48e7-bc06-3829576d606f.jpeg)
![Tlite3](https://user-images.githubusercontent.com/21012635/228972482-109a63e4-413d-4f54-a360-4b90facb0550.jpeg)
![Tlite2](https://user-images.githubusercontent.com/21012635/228972484-97dbdd95-9f79-4b8b-bef9-52bb5589d5f6.jpeg)
![Tlite1](https://user-images.githubusercontent.com/21012635/228972485-29536f95-388c-4873-998c-fd6f32fc23c3.jpeg)

https://user-images.githubusercontent.com/21012635/228972489-108d63f7-4b26-4148-8895-4a2f1d814405.mp4

Reducing the read frequency (1Hz) and using lower temp as ref.:

https://user-images.githubusercontent.com/21012635/228974744-8af5932f-ef16-4c85-8316-3e27f53728f4.mov

### Environment

- FW version: 0.0.7

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [x] My report contains all necessary details

**Comment by lovyan03** [comment]
Hello, @danilotomaccio 
Thanks for bringing this issue to our attention.
In v0.0.7, the process of interpolating damaged pixels on the sensor was not working properly.
In v0.0.8, this Issue has been resolved.

The code in this repository is already in v0.0.8, so it should work by building and writing as is.
Since v0.0.8 has been released in M5BurnerV3, you can also use it.

![image](https://user-images.githubusercontent.com/42724151/229694203-33b81074-ddcb-4f6d-8db4-62b86c5c1cdb.png)
